<?php
session_start();
require_once 'db_connect.php';

// Timezone to Philippines
date_default_timezone_set('Asia/Manila'); 

if (!isset($_SESSION['admin_id'])) {
    header("Location: admin_login.php");
    exit();
}

$sql = "SELECT * FROM lost_items ORDER BY date_lost DESC";
$result = $conn->query($sql);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lost Items Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');
        body { font-family: 'Poppins', sans-serif; }
        .watermark {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 80%;    
            max-width: 600px; 
            opacity: 0.15; 
            z-index: -1; 
            pointer-events: none;
        }
        @media print {
            .no-print { display: none; }
            body { 
                background: white; 
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
            table { width: 100%; border-collapse: collapse; }
            th, td { border: 1px solid #000; padding: 8px; font-size: 12px; }
            th { background-color: #f3f4f6 !important; }
        }
    </style>
</head>
<body class="bg-white p-10 max-w-5xl mx-auto relative min-h-screen">

    <img src="mcti_logo.png" class="watermark" alt="Watermark">

    <div class="flex justify-between items-end mb-8 border-b-2 border-black pb-4 relative z-10">
        <div>
            <h1 class="text-3xl font-bold uppercase tracking-wider text-black">Lost Items Report</h1>
            <p class="text-sm text-gray-600 font-medium mt-1">Marvelous College of Technology, Inc. - Lost & Found System</p>
        </div>
        <div class="text-right">
            <p class="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Date Generated</p>
            <p class="font-bold text-lg text-black"><?php echo date('F d, Y h:i A'); ?></p>
        </div>
    </div>

    <table class="w-full text-left border border-black relative z-10 bg-transparent">
        <thead>
            <tr class="bg-gray-100">
                <th class="border border-black p-3 text-xs font-bold uppercase">Item Name</th>
                <th class="border border-black p-3 text-xs font-bold uppercase">Category</th>
                <th class="border border-black p-3 text-xs font-bold uppercase">Reported By (Student)</th>
                <th class="border border-black p-3 text-xs font-bold uppercase">Location</th>
                <th class="border border-black p-3 text-xs font-bold uppercase">Date Lost</th>
                <th class="border border-black p-3 text-xs font-bold uppercase">Status</th>
            </tr>
        </thead>
        <tbody>
            <?php if ($result->num_rows > 0): ?>
                <?php while($row = $result->fetch_assoc()): ?>
                <tr class="bg-white/60"> <td class="border border-black p-3 font-bold text-black"><?php echo htmlspecialchars($row['item_name']); ?></td>
                    <td class="border border-black p-3 text-sm text-black"><?php echo htmlspecialchars($row['category']); ?></td>
                    <td class="border border-black p-3 text-sm font-semibold text-black">
                        <?php echo htmlspecialchars($row['reporter_name']); ?>
                    </td>
                    <td class="border border-black p-3 text-sm text-black"><?php echo htmlspecialchars($row['location']); ?></td>
                    <td class="border border-black p-3 text-sm font-mono text-black">
                        <?php echo date('M d, Y', strtotime($row['date_lost'])); ?>
                    </td>
                    <td class="border border-black p-3 text-xs font-bold uppercase text-center text-black">
                        <?php echo htmlspecialchars($row['status']); ?>
                    </td>
                </tr>
                <?php endwhile; ?>
            <?php else: ?>
                <tr>
                    <td colspan="6" class="border border-black p-8 text-center text-gray-500 italic">No records found.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="mt-16 grid grid-cols-2 gap-20 relative z-10">
        <div>
            <p class="text-xs font-bold uppercase mb-8">Generated By:</p>
            <div class="border-b border-black w-full"></div>
            <p class="text-sm mt-1">Administrator Signature</p>
        </div>
        <div>
            <p class="text-xs font-bold uppercase mb-8">Verified By:</p>
            <div class="border-b border-black w-full"></div>
            <p class="text-sm mt-1">SAO Officer Signature</p>
        </div>
    </div>

    <div class="fixed bottom-8 right-8 no-print z-50">
        <button onclick="window.print()" class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded-full shadow-2xl flex items-center gap-2 transform hover:scale-105 transition">
            <i class="fas fa-print"></i> Print Now
        </button>
    </div>

</body>
</html>